default_config:
media_source:
stream:
wake_on_lan:
homeassistant:
  customize: !include customize.yaml
frontend:
    themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
camera: !include camera.yaml

tts:
  - platform: google_translate

history:
  include:
    domains:
      - sensor
      - input_boolean
      - binary_sensor
      - switch
      - media_player

recorder:
  purge_keep_days: 5
  purge_interval: 2

alarm_control_panel:
  - platform: manual
    name: Alarme
    code: !secret alarm_code
    trigger_time: 100

influxdb: !include influxdb.yaml
octoprint: !include octoprint.yaml
garbage_collection: !include garbage_collection.yaml

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
    client_id: !secret google_calendar_clientid
    client_secret: !secret google_calendar_secret

