# Describes the format for available water_heater services

set_away_mode:
  description: Turn away mode on/off for water_heater device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "water_heater.water_heater"
    time_period:
      description: Number of away days
      example: 7

set_boost_mode:
  description: Turn boost mode on/off for water_heater device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "water_heater.water_heater"
    time_period:
      description: Number of boost days
      example: 2

set_operation_mode:
  description: Select operation mode for a boiler.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "water_heater.water_heater"
    mode:
      description: mode (operation mode list)
      example: stop
